-- V1__init.sql — initial rPulse schema.
--
-- REPLACE the contents of this file with your 15-table CREATE TABLE script.
-- While you are still authoring V1 (no real data yet), you can edit this file
-- freely and reset with:  docker compose down -v && docker compose up --build
--
-- Once V1 has been applied to a database you care about, DO NOT edit it again —
-- put every later change in a new file (V2__*.sql, V3__*.sql, ...) as an ALTER.
--
-- The placeholder table below just lets the stack boot until your script is ready;
-- delete it when you paste in your own DDL.

CREATE TABLE IF NOT EXISTS rpulse_placeholder (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
